In [558]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [559]:
df = pd.read_csv('rec_merged_apartments.csv')
df.head()

,apartment_name,zone,bhk_type,construction_status,carpet_area,bulit_area,super_bulit_area,price_value,nearbylocation,facility,luxury_facility_scores,luxury_category,Latitude,Longitude,apartment_loc,price_per_sqft,price_range,area_range
0,21st Castle Green Boulevard,east,3,Under Construction,NaN,1019.0,1134.00,0.67,"[('indus international school', '230 m'), ('sa...","['Squash Court', 'Yoga/Meditation Area', 'Bask...",51.0,medium,12.8925,77.7795,Sarjapur Road,5908.289242,50L-1Cr,1000-1500 sqft
1,2Gtula,east,3,Under Construction,NaN,1666.0,1854.00,1.52,"[('valistus international school', '5.9km'), (...","['Lounge', 'Creche/Day Care', ""Children's Play...",104.0,medium,12.9875,77.7085,Hoodi,8198.489752,1.5Cr-2Cr,1500-2000 sqft
2,A Grade,north,3,Under Construction,NaN,2157.0,2400.00,3.50,"['Mosque', 'Corporation bank ATM', 'Canara ban...","['Centrally Air Conditioned', 'Water purifier'...",84.0,medium,13.0365,77.5925,Hebbal,14583.333330,> 2Cr,2000-2500 sqft
3,ACS Meghana and Shali Apartments,south,2,Old,1372.0,1630.0,1837.01,1.50,"['Karnataka bank ATM', 'Syndicate bank ATM', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",136.0,medium,12.9412,77.5577,Banashankari Stage 2,8165.442758,1Cr-1.5Cr,1500-2000 sqft
4,AECS Layout RWA,north,4,Moderatly Old,2200.0,2614.0,2945.98,2.00,"['Sri Ramanjaneya Swamy Temple', 'Hdfc bank AT...","['Security / Fire Alarm', 'Lift(s)', 'Water St...",99.0,medium,13.0179,77.5766,Sanjayanagar,6788.912348,1.5Cr-2Cr,> 2500 sqft

In [560]:
df.columns

Index(['apartment_name', 'zone', 'bhk_type', 'construction_status',
       'carpet_area', 'bulit_area', 'super_bulit_area', 'price_value',
       'nearbylocation', 'facility', 'luxury_facility_scores',
       'luxury_category', 'Latitude', 'Longitude', 'apartment_loc',
       'price_per_sqft', 'price_range', 'area_range'],
      dtype='object')

In [561]:
df_sub = merged_df [['apartment_name','apartment_loc', 'facility']]

In [562]:
df_sub = df_sub.drop_duplicates(subset=['apartment_name','apartment_loc', 'facility'])

In [563]:
df_sub.loc[0][1]

C:\Users\amrpu\AppData\Local\Temp\ipykernel_21360\2782449505.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_sub.loc[0][1]

'Sarjapur Road'

In [564]:
df_sub

,apartment_name,apartment_loc,facility
0,21st Castle Green Boulevard,Sarjapur Road,"['Squash Court', 'Yoga/Meditation Area', 'Bask..."
1,2Gtula,Hoodi,"['Lounge', 'Creche/Day Care', ""Children's Play..."
2,A Grade,Hebbal,"['Centrally Air Conditioned', 'Water purifier'..."
3,ACS Meghana and Shali Apartments,Banashankari Stage 2,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,AECS Layout RWA,Sanjayanagar,"['Security / Fire Alarm', 'Lift(s)', 'Water St..."
...,...,...,...
1470,YMR Lichen,Kothanur,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1471,Yafa Zaifar,HBR Layout,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1472,Yuva Sunrise,Attibele,"['Security / Fire Alarm', 'Power Back-up', 'Fe..."
1473,Yuva Utsav,Electronics City Phase 2,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1474,Zen Indraprastha by Pratham,Yeshwanthpur,"['Security / Fire Alarm', 'Intercom Facility',..."

In [565]:
df_sub.drop_duplicates(subset=['apartment_name','apartment_loc'])

,apartment_name,apartment_loc,facility
0,21st Castle Green Boulevard,Sarjapur Road,"['Squash Court', 'Yoga/Meditation Area', 'Bask..."
1,2Gtula,Hoodi,"['Lounge', 'Creche/Day Care', ""Children's Play..."
2,A Grade,Hebbal,"['Centrally Air Conditioned', 'Water purifier'..."
3,ACS Meghana and Shali Apartments,Banashankari Stage 2,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,AECS Layout RWA,Sanjayanagar,"['Security / Fire Alarm', 'Lift(s)', 'Water St..."
...,...,...,...
1470,YMR Lichen,Kothanur,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1471,Yafa Zaifar,HBR Layout,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1472,Yuva Sunrise,Attibele,"['Security / Fire Alarm', 'Power Back-up', 'Fe..."
1473,Yuva Utsav,Electronics City Phase 2,"['Feng Shui / Vaastu Compliant', 'Security / F..."
1474,Zen Indraprastha by Pratham,Yeshwanthpur,"['Security / Fire Alarm', 'Intercom Facility',..."

In [567]:
import ast
# Function to safely parse the string representation of lists
def parse_facility_list(facility_str):
    """
    Safely parse the string representation of a list of facilities
    Handles both single and double quotes and strips whitespace
    """

    # Try using ast.literal_eval for safe parsing
    parsed_list = ast.literal_eval(facility_str)
    # Strip whitespace from each item
    return [item.replace(' ', '') for item in parsed_list]



# Parse the strings into actual Python lists
facilities = df_sub['facility'].apply(parse_facility_list).tolist()

# Convert lists to strings for TF-IDF processing
# This step is necessary because TfidfVectorizer expects text documents
facility_docs = [' '.join(facility) for facility in facilities]

In [569]:
facility_docs

["SquashCourt Yoga/MeditationArea BasketballCourt ClubHouse Children'sPlayArea SwimmingPool JoggingTrack LawnTennisCourt Gymnasium",
 "Lounge Creche/DayCare Children'sPlayArea SwimmingPool Park BanquetHall JoggingTrack Theatre Gymnasium",
 'CentrallyAirConditioned Waterpurifier Security/FireAlarm FengShui/VaastuCompliant PrivateGarden/Terrace IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff FalseCeilingLighting WaterStorage Separateentryforservantroom Noopendrainagearound Piped-gas Internet/wi-ficonnectivity RecentlyRenovated VisitorParking SwimmingPool Park NaturalLight AiryRooms SpaciousInteriors WasteDisposal RainWaterHarvesting Watersofteningplant ShoppingCentre FitnessCentre/GYM',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff WaterStorage Noopendrainagearound Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'Security/FireAlarm Lift(s) WaterStorage RainWaterHarvesting',
 'Security/FireAlarm Lift(s) WaterStorage',
 'Lift(s) MaintenanceStaff WaterStorage Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight AiryRooms FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 "Multipurposecourt SkatingRink Amphitheatre Children'sPlayArea SwimmingPool Park JoggingTrack MultipurposeHall Gymnasium",
 "Gymnasium AerobicsCentre ClubHouse Children'sPlayArea JoggingTrack Restaurant Library SwimmingPool Gazebo",
 'PowerBack-up IntercomFacility Lift(s) FitnessCentre/GYM Clubhouse/CommunityCenter',
 'Security/FireAlarm PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff FalseCeilingLighting WaterStorage Separateentryforservantroom Noopendrainagearound BankAttachedProperty Piped-gas Internet/wi-ficonnectivity VisitorParking SwimmingPool Park SecurityPersonnel LowDensitySociety WasteDisposal RainWaterHarvesting Watersofteningplant ShoppingCentre FitnessCentre/GYM Clubhouse/CommunityCenter',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) Waterpurifier MaintenanceStaff WaterStorage Noopendrainagearound RecentlyRenovated VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight SpaciousInteriors LowDensitySociety ShoppingCentre FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage VisitorParking',
 'Security/FireAlarm Lift(s) MaintenanceStaff Piped-gas VisitorParking SecurityPersonnel Internet/wi-ficonnectivity FitnessCentre/GYM WasteDisposal',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff WaterStorage Separateentryforservantroom Noopendrainagearound BankAttachedProperty Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors LowDensitySociety ShoppingCentre FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 "MultipurposeHall CarParking IndoorGames BanquetHall CommunityHall JoggingTrack SwimmingPool Children'sPlayArea Gymnasium",
 'PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) SwimmingPool Park Internet/wi-ficonnectivity FitnessCentre/GYM Clubhouse/CommunityCenter',
 'Security/FireAlarm FengShui/VaastuCompliant Lift(s) HighCeilingHeight MaintenanceStaff WaterStorage VisitorParking Park SecurityPersonnel NaturalLight AiryRooms LowDensitySociety FitnessCentre/GYM WasteDisposal Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage Park VisitorParking',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage Park VisitorParking',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage VisitorParking',
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) MaintenanceStaff WaterStorage',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff FalseCeilingLighting WaterStorage Separateentryforservantroom Noopendrainagearound Piped-gas VisitorParking SwimmingPool Park Internet/wi-ficonnectivity ShoppingCentre FitnessCentre/GYM WasteDisposal RainWaterHarvesting Watersofteningplant',
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) MaintenanceStaff WaterStorage Park VisitorParking',
 'PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) SwimmingPool Park FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 "Gymnasium Children'sPlayArea Amphitheatre SwimmingPool Creche/DayCare JoggingTrack SkatingRink Park Yoga/MeditationArea",
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage',
 'PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) SwimmingPool MaintenanceStaff Park SecurityPersonnel FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'IntercomFacility Lift(s) FengShui/VaastuCompliant Piped-gas SecurityPersonnel MaintenanceStaff SwimmingPool Park Clubhouse/CommunityCenter FitnessCentre/GYM',
 'Lift(s) MaintenanceStaff WaterStorage Park VisitorParking',
 'Security/FireAlarm FengShui/VaastuCompliant Lift(s) Waterpurifier HighCeilingHeight MaintenanceStaff WaterStorage Noopendrainagearound VisitorParking NaturalLight Internet/wi-ficonnectivity AiryRooms FitnessCentre/GYM RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 "GolfCourse ClubHouse Gymnasium Children'sPlayArea Amphitheatre SwimmingPool Creche/DayCare BanquetHall Park",
 'Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff FalseCeilingLighting SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity LowDensitySociety FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Lift(s) SwimmingPool Park VisitorParking FitnessCentre/GYM Clubhouse/CommunityCenter',
 "Gymnasium Park ClubHouse Children'sPlayArea JoggingTrack Amphitheatre SwimmingPool BadmintonCourt BasketballCourt",
 'Lift(s) SwimmingPool Park Piped-gas FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'FengShui/VaastuCompliant Lift(s) Noopendrainagearound SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors LowDensitySociety',
 'FengShui/VaastuCompliant Lift(s) WaterStorage VisitorParking',
 "Theatre Gymnasium Park ClubHouse BanquetHall Children'sPlayArea JoggingTrack SwimmingPool Gazebo",
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff SwimmingPool WaterStorage Park VisitorParking Internet/wi-ficonnectivity FitnessCentre/GYM Clubhouse/CommunityCenter',
 'PowerBack-up Lift(s) SwimmingPool Park Internet/wi-ficonnectivity FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'Security/FireAlarm Lift(s) MaintenanceStaff WaterStorage VisitorParking',
 'Security/FireAlarm VisitorParking',
 'Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff FalseCeilingLighting WaterStorage BankAttachedProperty VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors LowDensitySociety ShoppingCentre FitnessCentre/GYM RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 'Security/FireAlarm FengShui/VaastuCompliant Lift(s) MaintenanceStaff FalseCeilingLighting WaterStorage Noopendrainagearound RecentlyRenovated SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors ShoppingCentre FitnessCentre/GYM WasteDisposal RainWaterHarvesting',
 'PowerBack-up FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) SwimmingPool MaintenanceStaff WaterStorage Park VisitorParking FitnessCentre/GYM RainWaterHarvesting',
 'Security/FireAlarm PrivateGarden/Terrace IntercomFacility Lift(s) MaintenanceStaff FalseCeilingLighting WaterStorage VisitorParking Park NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors',
 'Security/FireAlarm FengShui/VaastuCompliant PrivateGarden/Terrace IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff FalseCeilingLighting WaterStorage Noopendrainagearound BankAttachedProperty Piped-gas Internet/wi-ficonnectivity VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors LowDensitySociety WasteDisposal RainWaterHarvesting Watersofteningplant ShoppingCentre FitnessCentre/GYM Clubhouse/CommunityCenter',
 'PowerBack-up FengShui/VaastuCompliant Lift(s) MaintenanceStaff Park SecurityPersonnel Clubhouse/CommunityCenter RainWaterHarvesting',
 "Lounge Children'sPlayArea BadmintonCourt Park GolfCourse Amphitheatre SwimmingPool ClubHouse Gymnasium",
 'PrivateGarden/Terrace Lift(s) SwimmingPool Park VisitorParking SecurityPersonnel Internet/wi-ficonnectivity ShoppingCentre FitnessCentre/GYM Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) MaintenanceStaff WaterStorage Park',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage Park VisitorParking',
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) WaterStorage',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff SwimmingPool WaterStorage Park VisitorParking ShoppingCentre FitnessCentre/GYM Watersofteningplant',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff WaterStorage VisitorParking SwimmingPool SecurityPersonnel NaturalLight AiryRooms LowDensitySociety FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 'PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff WaterStorage Noopendrainagearound SwimmingPool Park NaturalLight AiryRooms FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'Security/FireAlarm Lift(s) MaintenanceStaff SwimmingPool WaterStorage Noopendrainagearound SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors FitnessCentre/GYM Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Lift(s) FalseCeilingLighting WaterStorage RecentlyRenovated SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors WasteDisposal',
 "BadmintonCourt BasketballCourt ClubHouse Children'sPlayArea SwimmingPool Park JoggingTrack MultipurposeHall Gymnasium",
 "MultipurposeHall BasketballCourt BadmintonCourt Children'sPlayArea Gymnasium ClubHouse SwimmingPool Park JoggingTrack",
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) MaintenanceStaff WaterStorage',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage',
 'FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff Park SecurityPersonnel FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) WaterStorage',
 'Security/FireAlarm IntercomFacility Lift(s) WaterStorage VisitorParking',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff WaterStorage Noopendrainagearound Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors LowDensitySociety FitnessCentre/GYM RainWaterHarvesting Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Lift(s) Waterpurifier WaterStorage Noopendrainagearound RecentlyRenovated NaturalLight AiryRooms Internet/wi-ficonnectivity SpaciousInteriors LowDensitySociety RainWaterHarvesting',
 'Security/FireAlarm FengShui/VaastuCompliant PrivateGarden/Terrace IntercomFacility Lift(s) CentrallyAirConditioned Waterpurifier WaterStorage BankAttachedProperty Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel Internet/wi-ficonnectivity ShoppingCentre FitnessCentre/GYM WasteDisposal Clubhouse/CommunityCenter Watersofteningplant',
 'FengShui/VaastuCompliant Lift(s) MaintenanceStaff SwimmingPool Park VisitorParking FitnessCentre/GYM',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff SwimmingPool WaterStorage Park VisitorParking ShoppingCentre FitnessCentre/GYM Watersofteningplant',
 'Lift(s) MaintenanceStaff WaterStorage',
 'Security/FireAlarm PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff WaterStorage Separateentryforservantroom Noopendrainagearound Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel Internet/wi-ficonnectivity ShoppingCentre FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 'PrivateGarden/Terrace IntercomFacility Lift(s) MaintenanceStaff SwimmingPool WaterStorage Park SecurityPersonnel FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'Security/FireAlarm PowerBack-up Lift(s) MaintenanceStaff WaterStorage Noopendrainagearound VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 'PowerBack-up IntercomFacility Lift(s) SwimmingPool Park Piped-gas FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff Noopendrainagearound RecentlyRenovated BankAttachedProperty SwimmingPool Park SecurityPersonnel NaturalLight AiryRooms Internet/wi-ficonnectivity SpaciousInteriors FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'Security/FireAlarm IntercomFacility Lift(s) Waterpurifier MaintenanceStaff Noopendrainagearound SwimmingPool Park SecurityPersonnel NaturalLight FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff WaterStorage Noopendrainagearound VisitorParking SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors LowDensitySociety WasteDisposal RainWaterHarvesting',
 "TerraceGarden Children'sPlayArea BasketballCourt SwimmingPool Park JoggingTrack ClubHouse Yoga/MeditationArea Gymnasium",
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) SwimmingPool MaintenanceStaff WaterStorage Park VisitorParking ShoppingCentre FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'Security/FireAlarm FengShui/VaastuCompliant PrivateGarden/Terrace IntercomFacility Lift(s) MaintenanceStaff WaterStorage Separateentryforservantroom Noopendrainagearound Piped-gas VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms LowDensitySociety FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 'IntercomFacility Lift(s) MaintenanceStaff Park SecurityPersonnel FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting Watersofteningplant',
 'Security/FireAlarm MaintenanceStaff WaterStorage Piped-gas VisitorParking',
 'FengShui/VaastuCompliant IntercomFacility Lift(s) WaterStorage',
 "ClubHouse Gymnasium Children'sPlayArea SwimmingPool Creche/DayCare Theatre BanquetHall Lounge Park",
 'PowerBack-up Lift(s) SwimmingPool FitnessCentre/GYM Clubhouse/CommunityCenter',
 'Lift(s) Park FitnessCentre/GYM Clubhouse/CommunityCenter',
 'PrivateGarden/Terrace Lift(s) Waterpurifier HighCeilingHeight FalseCeilingLighting Separateentryforservantroom Noopendrainagearound Piped-gas SwimmingPool SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors LowDensitySociety FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 "Gymnasium BanquetHall Children'sPlayArea Yoga/MeditationArea PartyLawn SwimmingPool BadmintonCourt Creche/DayCare BasketballCourt",
 'Security/FireAlarm FengShui/VaastuCompliant IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff FalseCeilingLighting WaterStorage Piped-gas VisitorParking SwimmingPool Park Internet/wi-ficonnectivity Clubhouse/CommunityCenter',
 'Security/FireAlarm PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff WaterStorage Noopendrainagearound SwimmingPool Park SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors ShoppingCentre FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter Watersofteningplant',
 'PowerBack-up IntercomFacility SwimmingPool Park NaturalLight AiryRooms FitnessCentre/GYM Clubhouse/CommunityCenter',
 'CentrallyAirConditioned Waterpurifier Security/FireAlarm FengShui/VaastuCompliant PrivateGarden/Terrace IntercomFacility Lift(s) HighCeilingHeight MaintenanceStaff FalseCeilingLighting WaterStorage Separateentryforservantroom Noopendrainagearound BankAttachedProperty Piped-gas Internet/wi-ficonnectivity RecentlyRenovated VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors LowDensitySociety WasteDisposal RainWaterHarvesting Watersofteningplant ShoppingCentre FitnessCentre/GYM Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff WaterStorage WasteDisposal RainWaterHarvesting',
 'Security/FireAlarm Lift(s) MaintenanceStaff VisitorParking',
 "Children'sPlayArea BasketballCourt Park JoggingTrack BadmintonCourt ClubHouse BanquetHall CricketPitch Gymnasium",
 'Security/FireAlarm FengShui/VaastuCompliant PrivateGarden/Terrace IntercomFacility Lift(s) MaintenanceStaff WaterStorage Noopendrainagearound VisitorParking SwimmingPool Park SecurityPersonnel NaturalLight AiryRooms SpaciousInteriors LowDensitySociety FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'FengShui/VaastuCompliant Security/FireAlarm Lift(s) MaintenanceStaff SwimmingPool WaterStorage Park VisitorParking ShoppingCentre FitnessCentre/GYM Watersofteningplant',
 'Security/FireAlarm PowerBack-up FengShui/VaastuCompliant IntercomFacility Lift(s) MaintenanceStaff FalseCeilingLighting WaterStorage Noopendrainagearound VisitorParking SwimmingPool Park NaturalLight AiryRooms Internet/wi-ficonnectivity SpaciousInteriors LowDensitySociety FitnessCentre/GYM WasteDisposal RainWaterHarvesting Clubhouse/CommunityCenter',
 'PowerBack-up IntercomFacility Lift(s) SwimmingPool MaintenanceStaff Park SecurityPersonnel Internet/wi-ficonnectivity FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting',
 'Security/FireAlarm IntercomFacility Lift(s) MaintenanceStaff SwimmingPool Park SecurityPersonnel Clubhouse/CommunityCenter',
 'Security/FireAlarm IntercomFacility Lift(s) WaterStorage Noopendrainagearound BankAttachedProperty VisitorParking SecurityPersonnel NaturalLight Internet/wi-ficonnectivity AiryRooms SpaciousInteriors WasteDisposal RainWaterHarvesting',
 'Security/FireAlarm SwimmingPool VisitorParking',
 'Lift(s) MaintenanceStaff Park',
 'FengShui/VaastuCompliant Lift(s) WaterStorage Noopendrainagearound Piped-gas WasteDisposal RainWaterHarvesting',
 'Lift(s) VisitorParking SecurityPersonnel',
 'PowerBack-up FengShui/VaastuCompliant Lift(s) RainWaterHarvesting',
 'PowerBack-up IntercomFacility Lift(s) SwimmingPool Park FitnessCentre/GYM RainWaterHarvesting',
 'FengShui/VaastuCompliant Lift(s) SwimmingPool WaterStorage Park NaturalLight AiryRooms SpaciousInteriors FitnessCentre/GYM Clubhouse/CommunityCenter WasteDisposal RainWaterHarvesting',
 'FengShui/VaastuCompliant IntercomFacility Lift(s) SwimmingPool Park Piped-gas Internet/wi-ficonnectivity ShoppingCentre FitnessCentre/GYM Clubhouse/CommunityCenter RainWaterHarvesting Watersofteningplant',

In [570]:
vectorizer = TfidfVectorizer(lowercase=False)  # Keeping original case to preserve exact amenity names
tfidf_matrix = vectorizer.fit_transform(facility_docs)

In [571]:
# Get feature names (amenities)
feature_names = vectorizer.get_feature_names_out()

# Create a DataFrame with TF-IDF scores
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

In [572]:
df_tfidf

,24,24x7Security,7PowerBackup,7WaterSupply,AerobicsCentre,AiryRooms,Amphitheatre,BadmintonCourt,BankAttachedProperty,BanquetHall,...,WaterStorage,Waterpurifier,Watersofteningplant,Wi,Yoga,ficonnectivity,gas,sPlayArea,up,wi
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.0,0.320165,0.000000,0.000000,0.235110,0.000000,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.338651,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.245647,0.000000,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.160267,0.0,0.0,0.0,0.000000,...,0.107399,0.243352,0.169030,0.0,0.000000,0.172618,0.172388,0.000000,0.000000,0.172618
3,0.0,0.0,0.0,0.0,0.0,0.232615,0.0,0.0,0.0,0.000000,...,0.155881,0.000000,0.000000,0.0,0.000000,0.250541,0.250207,0.000000,0.000000,0.250541
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.458274,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.251725,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1471,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.260260,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1472,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.221535,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.346431,0.000000
1473,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.362066,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1474,0.0,0.0,0.0,0.0,0.0,0.251035,0.0,0.0,0.0,0.000000,...,0.168225,0.000000,0.264761,0.0,0.000000,0.270381,0.000000,0.000000,0.000000,0.270381

In [573]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [574]:
cosine_sim1.shape

(1475, 1475)

In [575]:
def recommend_properties(property_name, cosine_sim=cosine_sim1):
    # Get the index of the property that matches the name
    idx = df_sub[df_sub['apartment_name'] == property_name].index[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df_sub['apartment_name'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [576]:
recommend_properties('MJR Pearl')

                  PropertyName             SimilarityScore
778              Mythri Arteor   (778, 0.9123292648721808)
207    Brigade Golden Triangle   (207, 0.9010274077785041)
966   Purva Midtown Residences   (966, 0.8813361044776822)
401        Fortuna Center Park   (401, 0.8490177775591441)
1280              Sobha Althea  (1280, 0.8490177775591441)

In [577]:
df_sub_2 = df[['apartment_name','apartment_loc','bhk_type','bulit_area','price_value']]

In [578]:
df_sub_2 = df_sub_2.drop_duplicates(subset=['apartment_name','apartment_loc'])

In [579]:
df_sub_2  = df_sub_2.drop(columns=['apartment_loc'])

In [580]:
df_sub_2.head()

                     apartment_name  bhk_type  bulit_area  price_value
0       21st Castle Green Boulevard         3      1019.0         0.67
1                            2Gtula         3      1666.0         1.52
2                           A Grade         3      2157.0         3.50
3  ACS Meghana and Shali Apartments         2      1630.0         1.50
4                   AECS Layout RWA         4      2614.0         2.00

In [581]:
# First, let's pivot the built_area
pivot_area = df_sub_2.pivot_table(
    index='apartment_name', 
    columns='bhk_type', 
    values='bulit_area',
    aggfunc='first'  # Use 'first' as aggregation function
).reset_index()

In [582]:
pivot_area

bhk_type                    apartment_name      1       2       3       4
0              21st Castle Green Boulevard    NaN     NaN  1019.0     NaN
1                                   2Gtula    NaN     NaN  1666.0     NaN
2                                  A Grade    NaN     NaN  2157.0     NaN
3         ACS Meghana and Shali Apartments    NaN  1630.0     NaN     NaN
4                          AECS Layout RWA    NaN     NaN     NaN  2614.0
...                                    ...    ...     ...     ...     ...
1470                            YMR Lichen    NaN  1044.0     NaN     NaN
1471                           Yafa Zaifar    NaN     NaN  2950.0     NaN
1472                          Yuva Sunrise  924.0     NaN     NaN     NaN
1473                            Yuva Utsav    NaN     NaN  1302.0     NaN
1474           Zen Indraprastha by Pratham    NaN  1503.0     NaN     NaN

[1475 rows x 5 columns]

In [583]:

pivot_area.columns = ['apartment_name'] + [f'area_{col}_bhk' for col in pivot_area.columns if col != 'apartment_name']

In [584]:
pivot_area

,apartment_name,area_1_bhk,area_2_bhk,area_3_bhk,area_4_bhk
0,21st Castle Green Boulevard,NaN,NaN,1019.0,NaN
1,2Gtula,NaN,NaN,1666.0,NaN
2,A Grade,NaN,NaN,2157.0,NaN
3,ACS Meghana and Shali Apartments,NaN,1630.0,NaN,NaN
4,AECS Layout RWA,NaN,NaN,NaN,2614.0
...,...,...,...,...,...
1470,YMR Lichen,NaN,1044.0,NaN,NaN
1471,Yafa Zaifar,NaN,NaN,2950.0,NaN
1472,Yuva Sunrise,924.0,NaN,NaN,NaN
1473,Yuva Utsav,NaN,NaN,1302.0,NaN
1474,Zen Indraprastha by Pratham,NaN,1503.0,NaN,NaN

In [585]:
# Now pivot the price_value
pivot_price = df_sub_2.pivot_table(
    index='apartment_name', 
    columns='bhk_type', 
    values='price_value',
    aggfunc='first'  # Use 'first' as aggregation function
).reset_index()

# Rename the columns to include "price_" prefix for bhk_type columns
pivot_price.columns = ['apartment_name'] + [f'price_{col}_bhk' for col in pivot_price.columns if col != 'apartment_name']

In [586]:
# Merge the pivoted dataframes
result = pd.merge(pivot_area, pivot_price.drop('apartment_name', axis=1), left_index=True, right_index=True)

print("\nPivoted dataframe (wide format):")

Pivoted dataframe (wide format):

In [587]:
result

,apartment_name,area_1_bhk,area_2_bhk,area_3_bhk,area_4_bhk,price_1_bhk,price_2_bhk,price_3_bhk,price_4_bhk
0,21st Castle Green Boulevard,NaN,NaN,1019.0,NaN,NaN,NaN,0.67,NaN
1,2Gtula,NaN,NaN,1666.0,NaN,NaN,NaN,1.52,NaN
2,A Grade,NaN,NaN,2157.0,NaN,NaN,NaN,3.50,NaN
3,ACS Meghana and Shali Apartments,NaN,1630.0,NaN,NaN,NaN,1.50,NaN,NaN
4,AECS Layout RWA,NaN,NaN,NaN,2614.0,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...
1470,YMR Lichen,NaN,1044.0,NaN,NaN,NaN,0.75,NaN,NaN
1471,Yafa Zaifar,NaN,NaN,2950.0,NaN,NaN,NaN,2.20,NaN
1472,Yuva Sunrise,924.0,NaN,NaN,NaN,0.39,NaN,NaN,NaN
1473,Yuva Utsav,NaN,NaN,1302.0,NaN,NaN,NaN,0.65,NaN
1474,Zen Indraprastha by Pratham,NaN,1503.0,NaN,NaN,NaN,2.94,NaN,NaN

In [588]:
result=result.fillna(0)

In [589]:
result = result.set_index('apartment_name')

In [590]:
from sklearn.preprocessing import StandardScaler

# Compute the cosine similarity matrix

scaler = StandardScaler()
result_scaled = scaler.fit_transform(result)

In [591]:
# Convert the scaled array back to a Pandas DataFrame
result_scaled_df = pd.DataFrame(result_scaled, columns=result.columns, index=result.index)

# Display the DataFrame
result_scaled_df.head()

,area_1_bhk,area_2_bhk,area_3_bhk,area_4_bhk,price_1_bhk,price_2_bhk,price_3_bhk,price_4_bhk
apartment_name,,,,,,,,
21st Castle Green Boulevard,-0.279855,-0.997728,0.518237,-0.215819,-0.242603,-0.837263,0.052283,-0.198834
2Gtula,-0.279855,-0.997728,1.292956,-0.215819,-0.242603,-0.837263,0.844325,-0.198834
A Grade,-0.279855,-0.997728,1.880881,-0.215819,-0.242603,-0.837263,2.689317,-0.198834
ACS Meghana and Shali Apartments,-0.279855,1.797423,-0.701917,-0.215819,-0.242603,1.756143,-0.572033,-0.198834
AECS Layout RWA,-0.279855,-0.997728,-0.701917,3.468330,-0.242603,-0.837263,-0.572033,1.629536

In [592]:
cosine_sim2 = cosine_similarity(result_scaled)

In [593]:
cosine_sim2.shape

(1475, 1475)

In [594]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim2[result_scaled_df.index.get_loc(property_name)]))

    print(sim_scores)
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = result_scaled_df.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

In [595]:
recommend_properties_with_scores('MJR Pearl')

[(0, np.float64(-0.046518679866498415)), (1, np.float64(-0.12778840890901041)), (2, np.float64(-0.15556279272792445)), (3, np.float64(-0.29731903049018676)), (4, np.float64(-0.013939926508218703)), (5, np.float64(-0.08015175338461893)), (6, np.float64(-0.2774556830185229)), (7, np.float64(-0.05934204103957134)), (8, np.float64(-0.29402789288236836)), (9, np.float64(-0.24065119802549406)), (10, np.float64(-0.2899669036986905)), (11, np.float64(-0.2900379433370583)), (12, np.float64(-0.2821607122138421)), (13, np.float64(-0.09393929204525117)), (14, np.float64(-0.13214992751908924)), (15, np.float64(-0.24527330346875606)), (16, np.float64(-0.2904401325970519)), (17, np.float64(-0.2775003868855756)), (18, np.float64(0.8621537299915025)), (19, np.float64(-0.07210220519309773)), (20, np.float64(-0.21663192336425108)), (21, np.float64(-0.07286147106688577)), (22, np.float64(-0.04726228682330042)), (23, np.float64(-0.19099439111356323)), (24, np.float64(-0.0612314644393318)), (25, np.float64(-0.2942981611482755)), (26, np.float64(-0.300089505929803)), (27, np.float64(-0.05224701087426675)), (28, np.float64(-0.1142709481496443)), (29, np.float64(-0.24490709452318832)), (30, np.float64(-0.1019795464548172)), (31, np.float64(-0.29317662110189324)), (32, np.float64(-0.2671277477144491)), (33, np.float64(-0.2824156086570681)), (34, np.float64(-0.2787374457367707)), (35, np.float64(-0.22644544081939436)), (36, np.float64(0.9898930723964479)), (37, np.float64(-0.2917780515504677)), (38, np.float64(-0.09740560643042193)), (39, np.float64(-0.2913574644601024)), (40, np.float64(0.9882049446644868)), (41, np.float64(-0.30013395893824685)), (42, np.float64(-0.26376467764362543)), (43, np.float64(-0.2386486653015857)), (44, np.float64(-0.134701687777959)), (45, np.float64(-0.29734821101731934)), (46, np.float64(-0.29936193511120535)), (47, np.float64(-0.029248142024100015)), (48, np.float64(-0.2957556498640563)), (49, np.float64(-0.2875514990671178)), (50, np.float64(-0.005063262345600416)), (51, np.float64(0.9922646684256716)), (52, np.float64(-0.2922038580853211)), (53, np.float64(-0.08462738882390297)), (54, np.float64(-0.07735331933554199)), (55, np.float64(-0.3023139144231292)), (56, np.float64(-0.11676506031293256)), (57, np.float64(-0.13415627196581956)), (58, np.float64(-0.10737024091331032)), (59, np.float64(-0.2904517231113559)), (60, np.float64(-0.10653182898014096)), (61, np.float64(-0.294775003466618)), (62, np.float64(-0.29538458187622807)), (63, np.float64(0.8583726131709335)), (64, np.float64(-0.2852966181530782)), (65, np.float64(-0.10653737684789055)), (66, np.float64(-0.09180079780080819)), (67, np.float64(-0.2943073615910097)), (68, np.float64(-0.30228684821560375)), (69, np.float64(-0.14556520638705958)), (70, np.float64(-0.10483238662023107)), (71, np.float64(-0.2826327991544911)), (72, np.float64(-0.12232488304550894)), (73, np.float64(-0.09856083628846855)), (74, np.float64(-0.07325486209193431)), (75, np.float64(-0.12105644687083811)), (76, np.float64(-0.1283630725779152)), (77, np.float64(-0.297480032207501)), (78, np.float64(-0.2737034841514974)), (79, np.float64(-0.3007639427666323)), (80, np.float64(-0.3010719652472455)), (81, np.float64(-0.12327757748864586)), (82, np.float64(-0.1322979161015884)), (83, np.float64(-0.1342160689200054)), (84, np.float64(-0.3011462864641495)), (85, np.float64(-0.056158357162396505)), (86, np.float64(-0.3017353217211458)), (87, np.float64(0.9423170674316416)), (88, np.float64(0.8819102296866447)), (89, np.float64(-0.15699604298779588)), (90, np.float64(-0.2955227580696129)), (91, np.float64(-0.10956956573486004)), (92, np.float64(-0.2724377009531307)), (93, np.float64(-0.14290712133854622)), (94, np.float64(-0.30000914861735295)), (95, np.float64(-0.0628513816589724)), (96, np.float64(-0.11008366907138764)), (97, np.float64(-0.30186407380341523)), (98, np.float64(-0.26301547758017346)), (99, np.float64(-0.11457610470756563)), (100, np.float64(0.9683466036807133)), (101, np.float64(-0.29570853422722354)), (102, np.float64(-0.3018020460366015)), (103, np.float64(-0.26463387754032874)), (104, np.float64(-0.2695229476867292)), (105, np.float64(-0.13561030113609468)), (106, np.float64(-0.1267087860582142)), (107, np.float64(-0.0907037805731802)), (108, np.float64(-0.2990995135818325)), (109, np.float64(0.004572486995350408)), (110, np.float64(-0.12690150209142528)), (111, np.float64(-0.29480678327439896)), (112, np.float64(-0.2875650303333746)), (113, np.float64(-0.12680672998296252)), (114, np.float64(-0.08308982669883967)), (115, np.float64(-0.1323270557761291)), (116, np.float64(-0.2832005309899613)), (117, np.float64(-0.13547478537002716)), (118, np.float64(-0.1253828310758693)), (119, np.float64(-0.13269928208765253)), (120, np.float64(-0.14593921442911434)), (121, np.float64(-0.1568888112995925)), (122, np.float64(-0.13123389680945147)), (123, np.float64(-0.1576262008289895)), (124, np.float64(-0.275451344713394)), (125, np.float64(-0.08944008074900829)), (126, np.float64(0.021280762876997407)), (127, np.float64(-0.08568840276975842)), (128, np.float64(-0.14762374740296105)), (129, np.float64(-0.29825663263354485)), (130, np.float64(-0.29872448673768354)), (131, np.float64(-0.2788252019343096)), (132, np.float64(-0.09649701276937839)), (133, np.float64(0.8822158035965547)), (134, np.float64(-0.2963601011693264)), (135, np.float64(-0.299788295152145)), (136, np.float64(-0.13612448160712767)), (137, np.float64(0.905436234688608)), (138, np.float64(0.95761504651522)), (139, np.float64(0.9281119985335295)), (140, np.float64(-0.1292874979764937)), (141, np.float64(-0.060573740348138505)), (142, np.float64(-0.25955980012136465)), (143, np.float64(-0.06630679968739582)), (144, np.float64(0.8667445886624339)), (145, np.float64(0.8503408748472207)), (146, np.float64(-0.2970312390527319)), (147, np.float64(0.9011301354554685)), (148, np.float64(0.873237510808437)), (149, np.float64(-0.08931251419641145)), (150, np.float64(-0.05100359169789135)), (151, np.float64(-0.29082454745315744)), (152, np.float64(-0.13522315758577905)), (153, np.float64(-0.020105559919396703)), (154, np.float64(-0.29038983614720576)), (155, np.float64(-0.29055696048582474)), (156, np.float64(-0.2736276487851232)), (157, np.float64(-0.29735718862189875)), (158, np.float64(-0.29459324558725136)), (159, np.float64(-0.29103915759411797)), (160, np.float64(-0.13110908022591966)), (161, np.float64(-0.29247566224839966)), (162, np.float64(-0.09690416666159617)), (163, np.float64(-0.11498724025015626)), (164, np.float64(0.9617911215831753)), (165, np.float64(-0.17107507804067526)), (166, np.float64(-0.14767674166151104)), (167, np.float64(-0.2965406956929462)), (168, np.float64(-0.08404326231342071)), (169, np.float64(-0.29274973174548663)), (170, np.float64(-0.13001058583004169)), (171, np.float64(-0.03843361160128192)), (172, np.float64(-0.10686053906095305)), (173, np.float64(-0.12703985754256508)), (174, np.float64(-0.29222447405047347)), (175, np.float64(-0.28149932187256105)), (176, np.float64(-0.08528449902002885)), (177, np.float64(-0.13188311482545903)), (178, np.float64(-0.2704313398448855)), (179, np.float64(-0.30062798302764493)), (180, np.float64(-0.29800579676292277)), (181, np.float64(-0.12606524091955967)), (182, np.float64(-0.13778124113328835)), (183, np.float64(-0.27574551543821313)), (184, np.float64(-0.15972491189356153)), (185, np.float64(-0.2947952421341502)), (186, np.float64(-0.09909040919954845)), (187, np.float64(-0.2655126493525162)), (188, np.float64(-0.27826613341314915)), (189, np.float64(-0.18753014600398632)), (190, np.float64(-0.29990474695907693)), (191, np.float64(-0.3015904443622978)), (192, np.float64(0.9880636797708965)), (193, np.float64(-0.29873432867546434)), (194, np.float64(-0.2869454052178689)), (195, np.float64(-0.12679072017548929)), (196, np.float64(-0.1506763126288646)), (197, np.float64(0.9995961432632872)), (198, np.float64(-0.2954370976540978)), (199, np.float64(-0.16448973080598125)), (200, np.float64(0.9995355569799181)), (201, np.float64(0.999202081921634)), (202, np.float64(0.9891745809053065)), (203, np.float64(-0.26314968052606047)), (204, np.float64(-0.16215536014951693)), (205, np.float64(-0.24418769679371655)), (206, np.float64(-0.12602035749433713)), (207, np.float64(-0.3006646574337519)), (208, np.float64(-0.07523643414466111)), (209, np.float64(-0.139505614545926)), (210, np.float64(-0.29618018694837833)), (211, np.float64(-0.1414723275732001)), (212, np.float64(-0.029646598912139725)), (213, np.float64(-0.02653842638853244)), (214, np.float64(-0.09157056119298615)), (215, np.float64(-0.1547833084564366)), (216, np.float64(-0.16067813214678936)), (217, np.float64(-0.008547212511661132)), (218, np.float64(-0.29272489198480245)), (219, np.float64(-0.2937748840192412)), (220, np.float64(-0.30019760241875076)), (221, np.float64(-0.3017761307397622)), (222, np.float64(-0.2873383291041776)), (223, np.float64(-0.29194845918365236)), (224, np.float64(-0.2722402162783028)), (225, np.float64(0.9954978496673171)), (226, np.float64(-0.11131799973669743)), (227, np.float64(-0.2545894945550474)), (228, np.float64(-0.2882330484301897)), (229, np.float64(-0.2867190175645113)), (230, np.float64(-0.06789695531900161)), (231, np.float64(-0.13776935923599098)), (232, np.float64(-0.15629706483296268)), (233, np.float64(-0.27483300449452214)), (234, np.float64(-0.296828424336051)), (235, np.float64(0.8930922141546785)), (236, np.float64(0.9842414499275516)), (237, np.float64(-0.2980485397410004)), (238, np.float64(-0.1457845993052954)), (239, np.float64(0.8958985801759425)), (240, np.float64(-0.28795543079973085)), (241, np.float64(0.9746305139874503)), (242, np.float64(-0.29254095820544757)), (243, np.float64(-0.0825149688942268)), (244, np.float64(-0.2792684855174701)), (245, np.float64(-0.255262804598652)), (246, np.float64(-0.11254567594801708)), (247, np.float64(-0.22327612354985304)), (248, np.float64(-0.23092269546965147)), (249, np.float64(-0.2807230753405189)), (250, np.float64(-0.27906288363175424)), (251, np.float64(-0.13996142007943008)), (252, np.float64(-0.2995080540305802)), (253, np.float64(-0.29713077816098943)), (254, np.float64(-0.0935418331993723)), (255, np.float64(-0.16416103115264685)), (256, np.float64(-0.03748477440665191)), (257, np.float64(-0.07506847891267589)), (258, np.float64(-0.03921573251650376)), (259, np.float64(-0.02662399639535438)), (260, np.float64(-0.28734519172410355)), (261, np.float64(-0.2848362481538439)), (262, np.float64(-0.27730978430498276)), (263, np.float64(-0.06842337314283951)), (264, np.float64(-0.2761092363996187)), (265, np.float64(-0.27667382136431373)), (266, np.float64(-0.29830876365161874)), (267, np.float64(-0.11282400006646864)), (268, np.float64(-0.298232973013141)), (269, np.float64(-0.29789625429641603)), (270, np.float64(-0.293687266502695)), (271, np.float64(0.8584835061654403)), (272, np.float64(-0.2776303174538606)), (273, np.float64(-0.2768161630687809)), (274, np.float64(-0.0815583774348417)), (275, np.float64(-0.13218162855663804)), (276, np.float64(-0.3010893142034085)), (277, np.float64(-0.3013493884566977)), (278, np.float64(-0.0799740204253773)), (279, np.float64(-0.10255949631548662)), (280, np.float64(-0.06799734774608553)), (281, np.float64(-0.2917070156697568)), (282, np.float64(-0.2737257095495415)), (283, np.float64(-0.25907170097489723)), (284, np.float64(-0.2995976349070005)), (285, np.float64(-0.09616988154072924)), (286, np.float64(-0.2745728954554407)), (287, np.float64(-0.2539917013742089)), (288, np.float64(-0.09639051663630731)), (289, np.float64(-0.2490014593078526)), (290, np.float64(-0.13863191572314273)), (291, np.float64(-0.2976425651036696)), (292, np.float64(-0.03326626476253884)), (293, np.float64(-0.300293112003901)), (294, np.float64(-0.2973166511524029)), (295, np.float64(-0.2614891373040581)), (296, np.float64(-0.2714424311604882)), (297, np.float64(-0.2962684234591966)), (298, np.float64(-0.27099534832832495)), (299, np.float64(-0.28457431207579237)), (300, np.float64(-0.19563387257441694)), (301, np.float64(-0.25994061017556924)), (302, np.float64(-0.29440383977372026)), (303, np.float64(-0.06698559676998667)), (304, np.float64(-0.09920879613460785)), (305, np.float64(-0.25890611904026856)), (306, np.float64(-0.08955429222957875)), (307, np.float64(-0.10317002315334015)), (308, np.float64(-0.2985687786126252)), (309, np.float64(-0.1416616369260793)), (310, np.float64(-0.2694380499193359)), (311, np.float64(-0.29652854895084757)), (312, np.float64(-0.058093328611385664)), (313, np.float64(-0.1408205176494353)), (314, np.float64(-0.2941755324869841)), (315, np.float64(-0.1503072844239225)), (316, np.float64(-0.06416980596692289)), (317, np.float64(-0.27826175749782595)), (318, np.float64(-0.05332449775098341)), (319, np.float64(-0.2200503331694873)), (320, np.float64(0.9010014024527574)), (321, np.float64(-0.26982108283553974)), (322, np.float64(-0.1130862866113506)), (323, np.float64(-0.2795488187167736)), (324, np.float64(-0.10608823528662573)), (325, np.float64(-0.28112875853698543)), (326, np.float64(-0.08053520270223995)), (327, np.float64(-0.041394094815085915)), (328, np.float64(-0.21855724958025924)), (329, np.float64(-0.3010186869997491)), (330, np.float64(-0.2867665510087539)), (331, np.float64(-0.29912084734647215)), (332, np.float64(-0.2926397191605134)), (333, np.float64(-0.2407180802544646)), (334, np.float64(-0.2962575370053979)), (335, np.float64(-0.2267114638746343)), (336, np.float64(-0.22513848919714238)), (337, np.float64(-0.2980464244116623)), (338, np.float64(-0.24841448402463687)), (339, np.float64(-0.22880771836956407)), (340, np.float64(-0.1261249237659072)), (341, np.float64(-0.2927072330584705)), (342, np.float64(-0.2932651866603161)), (343, np.float64(-0.28911843122389785)), (344, np.float64(-0.09359765405206985)), (345, np.float64(-0.13667441107686645)), (346, np.float64(-0.2985380881736919)), (347, np.float64(-0.2874455151451593)), (348, np.float64(-0.3011777181477746)), (349, np.float64(-0.28614384657778624)), (350, np.float64(-0.2702659215433923)), (351, np.float64(-0.2904802709620503)), (352, np.float64(-0.21628270033891406)), (353, np.float64(-0.08162455185539765)), (354, np.float64(-0.28526366718563057)), (355, np.float64(-0.2851878088356431)), (356, np.float64(-0.22033431139041454)), (357, np.float64(-0.22873827616587739)), (358, np.float64(-0.11782075186166018)), (359, np.float64(-0.1300993755893063)), (360, np.float64(-0.26326161628601125)), (361, np.float64(-0.10347727746289093)), (362, np.float64(-0.23499909182454998)), (363, np.float64(-0.0699521804567875)), (364, np.float64(-0.06478663956011894)), (365, np.float64(0.9660305112406374)), (366, np.float64(-0.22482490434423688)), (367, np.float64(-0.2973970514969619)), (368, np.float64(-0.29504648612348977)), (369, np.float64(0.94959856946257)), (370, np.float64(0.9996474636655426)), (371, np.float64(-0.28811239155259777)), (372, np.float64(-0.2987582198920596)), (373, np.float64(-0.24276328576771306)), (374, np.float64(-0.30007560315580317)), (375, np.float64(-0.2795157593938761)), (376, np.float64(-0.22825716321194417)), (377, np.float64(-0.13697059971314077)), (378, np.float64(-0.2642948016955343)), (379, np.float64(-0.2722621053516731)), (380, np.float64(-0.2821540029185535)), (381, np.float64(-0.15625290489260765)), (382, np.float64(-0.17228631063600916)), (383, np.float64(-0.2884464217514259)), (384, np.float64(-0.09475180902435787)), (385, np.float64(-0.11539927522410262)), (386, np.float64(-0.2952453244359894)), (387, np.float64(-0.1497606723262562)), (388, np.float64(-0.060268324109641655)), (389, np.float64(-0.10753316106341516)), (390, np.float64(-0.2900105812600307)), (391, np.float64(-0.2754639259018771)), (392, np.float64(-0.25544326842636406)), (393, np.float64(-0.02102436933948722)), (394, np.float64(-0.2593712862518646)), (395, np.float64(-0.0019928352342108626)), (396, np.float64(-0.29727733198256184)), (397, np.float64(-0.2646885287952058)), (398, np.float64(-0.1362382794805751)), (399, np.float64(-0.13774213727157728)), (400, np.float64(-0.08114241200739507)), (401, np.float64(-0.094540501961275)), (402, np.float64(-0.2927762651238943)), (403, np.float64(-0.2920456614870126)), (404, np.float64(-0.15063981543109584)), (405, np.float64(-0.2805337131761938)), (406, np.float64(-0.2965301916506161)), (407, np.float64(-0.14375588902042633)), (408, np.float64(-0.25932041905794084)), (409, np.float64(-0.07462784192081262)), (410, np.float64(-0.2833335845909158)), (411, np.float64(-0.10999868108103016)), (412, np.float64(-0.23353068987843223)), (413, np.float64(-0.25779892908886576)), (414, np.float64(-0.2328417378569272)), (415, np.float64(-0.27795443464888425)), (416, np.float64(-0.2940431284049171)), (417, np.float64(-0.2837682018798792)), (418, np.float64(-0.30154986091077196)), (419, np.float64(-0.14303413992754713)), (420, np.float64(-0.29508091297751526)), (421, np.float64(-0.29508091297751526)), (422, np.float64(-0.11264039116419236)), (423, np.float64(0.8499305826001448)), (424, np.float64(-0.07059657424663277)), (425, np.float64(-0.3001498428093941)), (426, np.float64(-0.29906365278360464)), (427, np.float64(-0.07059657424663277)), (428, np.float64(-0.10855209430157718)), (429, np.float64(-0.2918220988380905)), (430, np.float64(-0.2253615111815122)), (431, np.float64(-0.30032814102873046)), (432, np.float64(-0.23632788298877813)), (433, np.float64(-0.09645732652299727)), (434, np.float64(-0.08954531656139518)), (435, np.float64(-0.2843372574260129)), (436, np.float64(-0.14656892508174343)), (437, np.float64(-0.11418768437942457)), (438, np.float64(-0.267805458158423)), (439, np.float64(-0.07782870059035937)), (440, np.float64(-0.08048068953967907)), (441, np.float64(-0.2726816090476555)), (442, np.float64(-0.07800852860283826)), (443, np.float64(0.9909949765140178)), (444, np.float64(0.9968836202862532)), (445, np.float64(-0.29090874252146753)), (446, np.float64(-0.14466328282034852)), (447, np.float64(-0.29768964592907426)), (448, np.float64(-0.3000753132576182)), (449, np.float64(-0.2901607434108601)), (450, np.float64(-0.03450830750187969)), (451, np.float64(0.9999314844291013)), (452, np.float64(0.9970864382723323)), (453, np.float64(-0.16856716843506453)), (454, np.float64(0.9995967996577206)), (455, np.float64(-0.1509657736415092)), (456, np.float64(-0.1568728220617035)), (457, np.float64(-0.29945345001320245)), (458, np.float64(-0.2989417667746256)), (459, np.float64(-0.2918652837508458)), (460, np.float64(-0.277277977116102)), (461, np.float64(-0.15229545744241874)), (462, np.float64(-0.30243414704178895)), (463, np.float64(-0.28724174177540723)), (464, np.float64(-0.2698143875318036)), (465, np.float64(-0.290409638192763)), (466, np.float64(-0.16076455650730398)), (467, np.float64(-0.2843971260866798)), (468, np.float64(-0.10004553065860358)), (469, np.float64(-0.24562088225731135)), (470, np.float64(-0.2893805985346887)), (471, np.float64(-0.12831545848025963)), (472, np.float64(-0.13406384355273523)), (473, np.float64(-0.025553039511262515)), (474, np.float64(0.9909949765140178)), (475, np.float64(-0.11594091461849008)), (476, np.float64(-0.11467890069939699)), (477, np.float64(-0.2965235257841283)), (478, np.float64(-0.24894101156409204)), (479, np.float64(-0.12951391011947652)), (480, np.float64(0.8430131966669231)), (481, np.float64(-0.08116818365145484)), (482, np.float64(-0.11009272219854577)), (483, np.float64(-0.15449585995633858)), (484, np.float64(-0.10704587604491651)), (485, np.float64(-0.28299591561036475)), (486, np.float64(-0.2937907400973741)), (487, np.float64(-0.11484436474568799)), (488, np.float64(-0.29001510668136316)), (489, np.float64(-0.2818002497784993)), (490, np.float64(-0.10505097879653771)), (491, np.float64(-0.1604091103765736)), (492, np.float64(0.024080567526270122)), (493, np.float64(-0.3025126182751126)), (494, np.float64(-0.03376610436835853)), (495, np.float64(-0.14646845095594518)), (496, np.float64(-0.29926251029918727)),

                       PropertyName  SimilarityScore
0             Prestige Temple Bells         0.999986
1                    Godrej Nurture         0.999931
2                  SNN Raj Greenbay         0.999872
3                  TVS Emerald Jard         0.999845
4    Eden Park at The Prestige City         0.999647
..                              ...              ...
242                 Aarna Aplounder        -0.072102
243                  Aarna Splendor        -0.072861
244                 Radiant Spencer        -0.073253
245                    Aratt Milano        -0.073255
246                 Habilus Sunrise        -0.073801

[247 rows x 2 columns]

## based on nearby loc

In [618]:
df_sub_3 = pd.read_csv('rec_loc_merged_apartments.csv')

In [619]:
df_sub_3.head()

,apartment_name,nearbylocation
0,21st Castle Green Boulevard,"[('Indus International School', '230 m'), ('Az..."
1,2Gtula,"[('Valistus International School', '5.9 km'), ..."
2,A Grade,"[('Baptist Hospital', '1.5 km'), ('Poornima Ho..."
3,ACS Meghana and Shali Apartments,"[('Devagiri Hospital', '1.5 km'),('BNM Institu..."
4,AECS Layout RWA,"[('RMV Hospital', '1.5 km'), ('S. J. Hospital'..."

In [620]:
df_sub_3.shape

(1475, 2)

In [621]:
df_sub_3['nearbylocation'][0]

"[('Indus International School', '230 m'), ('Azim Premji University', '1.5 km'), ('Pandana Hospital', '5.6 km'), ('Heelalige Railway Station', '16.9 km'), ('Attibele Road', '3.2 km'), ('D Mart', '5.9 km'), ('Wipro Limited', '13.2 km')]"

In [622]:
import ast

def safe_literal_eval(val):
	try:
		return ast.literal_eval(val)
	except Exception:
		return None  # or [] if you prefer an empty list

df_sub_3['nearbylocation']=df_sub_3['nearbylocation'].apply(safe_literal_eval)

In [623]:
df_sub_3=df_sub_3.explode('nearbylocation')

In [624]:
df_sub_3

                   apartment_name                        nearbylocation
0     21st Castle Green Boulevard   (Indus International School, 230 m)
0     21st Castle Green Boulevard      (Azim Premji University, 1.5 km)
0     21st Castle Green Boulevard            (Pandana Hospital, 5.6 km)
0     21st Castle Green Boulevard  (Heelalige Railway Station, 16.9 km)
0     21st Castle Green Boulevard               (Attibele Road, 3.2 km)
...                           ...                                   ...
1474  Zen Indraprastha by Pratham   (Yeshwantpur Metro Station, 1.5 km)
1474  Zen Indraprastha by Pratham                  (Orion Mall, 2.0 km)
1474  Zen Indraprastha by Pratham      (National Public School, 1.8 km)
1474  Zen Indraprastha by Pratham            (Manipal Hospital, 2.0 km)
1474  Zen Indraprastha by Pratham             (Fortis Hospital, 2.0 km)

[8246 rows x 2 columns]

In [625]:
# df_expanded = df_sub_3.explode('nearbylocation')
df_sub_3['location_name'] = df_sub_3['nearbylocation'].apply(lambda x: x[0])
df_sub_3['distance'] = df_sub_3['nearbylocation'].apply(lambda x: x[1])

In [626]:
df_sub_3

,apartment_name,nearbylocation,location_name,distance
0,21st Castle Green Boulevard,"(Indus International School, 230 m)",Indus International School,230 m
0,21st Castle Green Boulevard,"(Azim Premji University, 1.5 km)",Azim Premji University,1.5 km
0,21st Castle Green Boulevard,"(Pandana Hospital, 5.6 km)",Pandana Hospital,5.6 km
0,21st Castle Green Boulevard,"(Heelalige Railway Station, 16.9 km)",Heelalige Railway Station,16.9 km
0,21st Castle Green Boulevard,"(Attibele Road, 3.2 km)",Attibele Road,3.2 km
...,...,...,...,...
1474,Zen Indraprastha by Pratham,"(Yeshwantpur Metro Station, 1.5 km)",Yeshwantpur Metro Station,1.5 km
1474,Zen Indraprastha by Pratham,"(Orion Mall, 2.0 km)",Orion Mall,2.0 km
1474,Zen Indraprastha by Pratham,"(National Public School, 1.8 km)",National Public School,1.8 km
1474,Zen Indraprastha by Pratham,"(Manipal Hospital, 2.0 km)",Manipal Hospital,2.0 km
1474,Zen Indraprastha by Pratham,"(Fortis Hospital, 2.0 km)",Fortis Hospital,2.0 km

In [627]:
def distance_converter(x):
    if 'km' in x.lower():
        return float(x.replace('km',''))*1000
    elif 'm' in x.lower():
        return float(x.replace('m','').strip())*1.0
    else:
        return 0

In [628]:
df_sub_3['distance']=df_sub_3['distance'].apply(distance_converter)

In [629]:
df_sub_3

,apartment_name,nearbylocation,location_name,distance
0,21st Castle Green Boulevard,"(Indus International School, 230 m)",Indus International School,230.0
0,21st Castle Green Boulevard,"(Azim Premji University, 1.5 km)",Azim Premji University,1500.0
0,21st Castle Green Boulevard,"(Pandana Hospital, 5.6 km)",Pandana Hospital,5600.0
0,21st Castle Green Boulevard,"(Heelalige Railway Station, 16.9 km)",Heelalige Railway Station,16900.0
0,21st Castle Green Boulevard,"(Attibele Road, 3.2 km)",Attibele Road,3200.0
...,...,...,...,...
1474,Zen Indraprastha by Pratham,"(Yeshwantpur Metro Station, 1.5 km)",Yeshwantpur Metro Station,1500.0
1474,Zen Indraprastha by Pratham,"(Orion Mall, 2.0 km)",Orion Mall,2000.0
1474,Zen Indraprastha by Pratham,"(National Public School, 1.8 km)",National Public School,1800.0
1474,Zen Indraprastha by Pratham,"(Manipal Hospital, 2.0 km)",Manipal Hospital,2000.0
1474,Zen Indraprastha by Pratham,"(Fortis Hospital, 2.0 km)",Fortis Hospital,2000.0

In [630]:
# Pivot the table using pivot_table to handle duplicates
df_sub_3=df_sub_3.pivot_table(
	index='apartment_name',
	columns='location_name',
	values='distance'
).reset_index()
df_sub_3

location_name,apartment_name,1 MG - Lido Mall,100 Feet Road,100 Feet Road Indiranagar,A.P.S. College of Engineering,AECS Maaruti College of Dental Sciences,AGS Layout Bus Stand,AI Vidya First Grade College,AIMS Institutes,AKASH Medical College,...,Yeshwantpur Market,Yeshwantpur Metro Station,Yesvantpur Bypass Station,Yesvantpur Junction,Yesvantpur Junction Railway Station,Yuvalok School,Zaitoon,Zeena English School,Zion Hospital And Research Centre,Zion Hospital and Research Centre
0,21st Castle Green Boulevard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2Gtula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A Grade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACS Meghana and Shali Apartments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AECS Layout RWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,YMR Lichen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1471,Yafa Zaifar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1472,Yuva Sunrise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1473,Yuva Utsav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1474,Zen Indraprastha by Pratham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [631]:
df_sub_3.columns

Index(['apartment_name', '1 MG - Lido Mall', '100 Feet Road',
       '100 Feet Road Indiranagar', 'A.P.S. College of Engineering',
       'AECS Maaruti College of Dental Sciences', 'AGS Layout Bus Stand',
       'AI Vidya First Grade College', 'AIMS Institutes',
       'AKASH Medical College',
       ...
       'Yeshwantpur Market', 'Yeshwantpur Metro Station',
       'Yesvantpur Bypass Station', 'Yesvantpur Junction',
       'Yesvantpur Junction Railway Station', 'Yuvalok School', 'Zaitoon',
       'Zeena English School', 'Zion Hospital And Research Centre',
       'Zion Hospital and Research Centre'],
      dtype='object', name='location_name', length=2073)

In [632]:
df_sub_3=df_sub_3.set_index('apartment_name')

In [633]:
df_sub_3.head()

location_name,1 MG - Lido Mall,100 Feet Road,100 Feet Road Indiranagar,A.P.S. College of Engineering,AECS Maaruti College of Dental Sciences,AGS Layout Bus Stand,AI Vidya First Grade College,AIMS Institutes,AKASH Medical College,AMC Engineering College,...,Yeshwantpur Market,Yeshwantpur Metro Station,Yesvantpur Bypass Station,Yesvantpur Junction,Yesvantpur Junction Railway Station,Yuvalok School,Zaitoon,Zeena English School,Zion Hospital And Research Centre,Zion Hospital and Research Centre
apartment_name,,,,,,,,,,,,,,,,,,,,,
21st Castle Green Boulevard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2Gtula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Grade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACS Meghana and Shali Apartments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AECS Layout RWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [634]:
df_sub_3 = df_sub_3.fillna(0)

In [635]:
from sklearn.preprocessing import StandardScaler
# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(df_sub_3), columns=df_sub_3.columns, index=df_sub_3.index)

In [636]:
location_df_normalized

location_name,1 MG - Lido Mall,100 Feet Road,100 Feet Road Indiranagar,A.P.S. College of Engineering,AECS Maaruti College of Dental Sciences,AGS Layout Bus Stand,AI Vidya First Grade College,AIMS Institutes,AKASH Medical College,AMC Engineering College,...,Yeshwantpur Market,Yeshwantpur Metro Station,Yesvantpur Bypass Station,Yesvantpur Junction,Yesvantpur Junction Railway Station,Yuvalok School,Zaitoon,Zeena English School,Zion Hospital And Research Centre,Zion Hospital and Research Centre
apartment_name,,,,,,,,,,,,,,,,,,,,,
21st Castle Green Boulevard,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
2Gtula,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
A Grade,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
ACS Meghana and Shali Apartments,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
AECS Layout RWA,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YMR Lichen,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
Yafa Zaifar,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
Yuva Sunrise,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
Yuva Utsav,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,-0.067665,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321
Zen Indraprastha by Pratham,-0.026047,-0.049266,-0.026047,-0.026047,-0.026047,-0.052146,-0.026047,-0.045087,-0.026047,-0.050994,...,-0.045145,12.203630,-0.026047,-0.026047,-0.036848,-0.071673,-0.026047,-0.026047,-0.026047,-0.058321

In [637]:


cosine_sim3 = cosine_similarity(location_df_normalized)

In [638]:
print(cosine_sim3.shape, cosine_sim2.shape, cosine_sim1.shape)

(1475, 1475) (1475, 1475) (1475, 1475)

In [639]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 30*cosine_sim1 + 8*cosine_sim3 + 2*cosine_sim2
    # cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

In [640]:
# Test the recommender function using a property name
recommend_properties_with_scores('AECS Layout RWA')

                  PropertyName  SimilarityScore
0             Casagrand Aquene        26.068945
1                   AM Classic        26.025994
2               Habitat Irenic        26.020929
3              Concord Heights        25.872290
4    Habilus Sunrise Apartment        25.683572
..                         ...              ...
242         Brigade Metropolis        15.467736
243               Payal Palace        15.465014
244        Ruchira Aarna Homes        15.430311
245           Vajram Newtown 2        15.381199
246             Perody Classic        15.366457

[247 rows x 2 columns]